Documentation:
  Enabled: false

LineLength:
  Max: 120

Lint/RescueException:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/PerceivedComplexity:
  Max: 8
