language: ruby
rvm:
  - 2.2.3
  - 2.5.1
  - jruby-19mode
  - jruby-head
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head

before_install:
  - gem update --system
  - gem install bundler -v 1.10.6
install: 'bundle'
script: 'bundle exec rake'
notifications:
  email:
    - pedro.carrico@gmail.com
